insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Fernando Cavenaghi','','Oriundo de O Brien, provincia de Buenos Aires. Pueblerino de honra, familiero, papá de tres encantos y enamorado de mi bella esposa. Viajero por trabajo y placer, me gusta emprender nuevos desafíos. En pleno proceso de descubrimiento del más allá. Estoy contento de ser parte de este hermoso grupo que inicia un nuevo camino a la solidaridad.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Emiliano Lobo','','Nací en el seno de una sencilla y hermosa familia. Mis primeros recuerdos son siempre junto a aquel primer y mejor amigo que me dio la vida, mi hermano mayor. Esas primeras y entrañables vivencias con muchas risas y algunas lágrimas marcaron a fuego lo que a futuro sería para mí el valor de la amistad, algo definitivamente necesario y fundamental.
A lo largo de los años esa hermosa familia de origen se fue haciendo más y más grande. La fui llenando de queridos amigos, y hoy con algunos de ellos formo parte de esta Fundación donde todos aquellos valores se hacen presentes. Juntos se hace posible lo imposible. Es poder contar para siempre con alguien, un privilegio. El mismo privilegio de ser parte de Ese Yo.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Valentin Gogorza','','Nací en la ciudad del frío, Tandil, un año antes del nuevo milenio. Soy periodista y entrenador de fútbol, deporte que le da sentido a mis días. Coqueteo con la filosofía cuando pregunto y con la psicología cuando observo. Valoro el silencio. Hace más de una década tenía 15 amigos que ahora son hermanos. Adoro a los perros y a mi familia. Me emociona integrar este equipo que surgió de la necesidad de ayudar.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Diego Placente','','Amante del fútbol y de la música. Nací en Villa Bosch, barrio de tanos de clase trabajadora. Anhelo que mis amigos se alegren cuando me vean venir. Creo en la cadena de favores. El mejor regalo que podemos dar a alguien es nuestro tiempo. Orgulloso de ser parte de Ese Yo.
');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Luciana Paola Cuesta','','Nací en Tandil. Hija de Clara y Pino, hermana de Nacho y Nico, y en el camino he sumado varios hermanos más. Elegí ser abogada, maestra de arte y buzo profesional. Amo bailar. Soy caprichosa y apasionada, ordenada en general y solidaria. Sé reír hasta las lágrimas y me emociono muy seguido también, defiendo mis convicciones y aprendo para seguir caminando.
Disfruto de jugar al fútbol, de entrenar en un ring de boxeo, de las flores, de los animales, del agua, de los abrazos, de los detalles, y siento fervientemente que todo lo que me llena el corazón es un reconocimiento de la vida, por eso lo custodio, lo agradezco y soy feliz.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Jose Dario Garce','','Hijo de Mabel y José. Creo en la vida y la oportunidad de poder transformar todo lo que siento que no está bien en mi vida, mientras me encuentro aquí, en esta tierra hermosa. Actuó como terapeuta, masajista y lector de aura. Soy aprendiz de música y canto y muchas cosas más.
Me gusta el deporte como esparcimiento. Medito a diario y me pregunto cada vez que me acuerdo: si hoy dejara esta forma de existencia, ¿estoy haciendo lo que quiero? ¿lo elijo? Hasta ahora sí.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Ivan Moreno y Fabianesi','','Padre de tres genialidades. Español de tierra y argentino de sangre. Deportista siempre. Entrenador. Consultor Deportivo. Coach Ontológico Profesional.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Emmanuel Alcala','','Me desarrollo como diseñador gráfico, ilustrador profesional y gestor cultural. Amante de la rica comida, acompaño a los que se animen en clases particulares presenciales/online. Formo parte de equipos que desarrollan contenido para las industrias creativas a nivel internacional.
Estoy a cargo Ciclotrazo, Ciclofoto junto a profesionales que brindan su tiempo y talento para crear nuevos universos mediante una narrativa interdisciplinaria. Soy un trabajador intenso, creo en el oficio del hacer, me baso en que toda experiencia es válida para construir un mejor presente y apuesto porque así sea.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Juan Pablo De Gregorio','','Orgullosamente nacido en la querida ciudad de Lobos. Amigo de mis amigos. Valoro la sencillez como la mayor de las virtudes. Estoy convencido de que el deporte educa e iguala. Todo sucede cuando tiene que suceder. Hacer más que contar. Feliz de formar parte de Ese Yo.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Ariel Garce','','Nací en Tandil. Padre de Valentín y Juana. Confió en que si lo das todo, algo va a pasar, que creamos nuestra realidad y que el universo conspira. Aprendiz de astrología y canto. Trabajos sociales, motos y autos de carreras son mis lindos disfrutes.');
insert into equipo (nombre, linkFoto, descripcionTrabajo) values ('Pablo Aimar','','Nací en Río Cuarto, Córdoba. Soy papá de cuatro hijos. Creo que dar una mano es siempre un buen plan. Formo parte con alegría de Ese Yo.');
